### ISSUE TITLE
Column Alignment is Off

### ISSUE THREAD

**Issue by micahlee** [MrSuborbian88/Arch_A1#6]
The column spec shows the columns as being left-aligned, but there appears to be alignment overlap because the timestamp value overflows to the next column.

**Comment by BlightOfYou** [comment]
If you're talking about the heading alignment, we need to decide if we want them tab separated or if they should visually line up. If you're talking about the value alignment, I don't think there's much we can do about that; the time string is just long.

**Comment by BlightOfYou** [comment]
Fixed.
