### ISSUE TITLE
Output filenames don't match the spec

### ISSUE THREAD

**Issue by micahlee** [MrSuborbian88/Arch_A1#7]
Specifically...

OutputA.dat

OutputB.dat
WildPoints.dat

OutputC.dat (System C doesn't actually give an output filename, but we might as well be consistent)

**Comment by BlightOfYou** [comment]
Bug fixed. See commit c04ac2801fbf430b87d3be8a1f5a8856ee267be4. Filenames are OutputA, OutputB, WildPoints, and OutputC.dat
